#!/bin/bash

set -o pipefail

. /opt/erlangelist/docker-helper.sh

cd /tmp
rm -rf erlangelist || true
git clone ~/erlangelist
cd erlangelist
docker/build-images.sh

function restart_if_needed {
  if [ $(/opt/erlangelist/$1.sh needs_restart) == "yes" ]; then
    echo "Restarting service $1"
    sudo systemctl restart $1
  else
    echo "$1 already running the latest version"
  fi
}

echo "restarting the main site"
sudo systemctl restart erlangelist-site
wait_for_site $(($ERLANGELIST_SITE_HTTP_PORT))
