Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.54.54"

  config.vm.provision :ansible do |ansible|
    ansible.verbose = 'v'
    ansible.playbook = "playbook.yml"
  end
end
